# Generated by Django 3.1.1 on 2020-09-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='provider',
            name='sdk',
            field=models.CharField(choices=[('TencentCloud', 'Tencent Cloud'), ('Aliyun', 'Alibaba Cloud')], default='TencentCloud', max_length=32),
        ),
    ]
