# Generated by Django 3.1.1 on 2020-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='sdk',
            field=models.CharField(choices=[('TencentCloud', 'Tencent Cloud'), ('Aliyun', 'Alibaba Cloud')], default='TencentCloud', max_length=32, unique=True),
        ),
    ]
