# Generated by Django 3.1.1 on 2020-09-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200923_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={},
        ),
        migrations.AlterField(
            model_name='zone',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.region'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('region', 'name')},
        ),
    ]
