# Generated by Django 3.1.1 on 2020-10-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201012_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=128)),
                ('service', models.CharField(max_length=128)),
                ('identity', models.IntegerField()),
                ('state', models.CharField(choices=[('WAITING', 'WAITING'), ('RUNNING', 'RUNNING'), ('SUCCEED', 'SUCCEED'), ('FAILED', 'FAILED')], default='WAITING', max_length=32)),
                ('retry_times', models.IntegerField(default=10)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
