# Generated by Django 3.1.1 on 2020-10-17 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('cidr', models.CharField(max_length=64, unique=True)),
                ('identity', models.CharField(max_length=64, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.provideraccount')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.region')),
            ],
            options={
                'unique_together': {('account', 'identity')},
            },
        ),
    ]
