# Generated by Django 3.1.1 on 2020-10-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_task'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnet',
            options={},
        ),
        migrations.AddField(
            model_name='subnet',
            name='cidr',
            field=models.CharField(default='', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='identity',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='name',
            field=models.CharField(default='', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='vpc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.vpc'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='subnet',
            unique_together={('vpc', 'identity')},
        ),
    ]
