# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from helloworld import helloworld_pb2 as helloworld_dot_helloworld__pb2


class GreeterStub(object):
    """声明 service 和 message

    service 声明的是服务 生成 xxx_pb2_grpc.py
    The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hellowold.Greeter/SayHello',
                request_serializer=helloworld_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld_dot_helloworld__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """声明 service 和 message

    service 声明的是服务 生成 xxx_pb2_grpc.py
    The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        rpc 声明一个方法 参数和返回值必须是 message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=helloworld_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=helloworld_dot_helloworld__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hellowold.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """声明 service 和 message

    service 声明的是服务 生成 xxx_pb2_grpc.py
    The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hellowold.Greeter/SayHello',
            helloworld_dot_helloworld__pb2.HelloRequest.SerializeToString,
            helloworld_dot_helloworld__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
